### ISSUE TITLE
Deployment pom file shows error for plugin maven-antrun-plugin

### ISSUE THREAD

**Issue by MartyBurns** [usnistgov/ucef-meta#7]
## Version information
fa471820415e64d9deca0bc4981e754ba48c0852 

## Observed behavior
When importing xxx_deployment projects into eclipse, the following error is shown in the top level pom.xml file:

`No marketplace entries found to handle maven-antrun-plugin:1.7:run in Eclipse.  Please see Help for more information.
`
The ant-run plugin allows for “ant” commands to be included in the pom file which, AFAIU, allows for directory creation and file copying.

This does not seem to be a problem for the Federates Exporter pom files, but is for the Deployment Exporter pom file.

## Expected behavior
Should not have errors

## Steps to reproduce issue
1. Create a federate(federation)
1. Do Federates Export
1. Do Deployment Export
1. Extract downloaded zip files
1. Create a new eclipse workspace
1. Import existing maven project from extracted project

The resulting XXX_exec project will show the error

**Comment by MartyBurns** [comment]
The problem can be resolved by wrapping the `<plugins></plugins>` tag in `<pluginManagement></pluginManagement>`.

See https://maven.apache.org/pom.html#Plugin_Management, and, https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

This can be resolved by adding the` <pluginManagement></pluginManagement>` to execution_pom.xml.ejs in the DeploymentExporter/Templates directory.

**Comment by tpr1** [comment]
done in https://github.com/usnistgov/ucef-meta/pull/10
